{% set name = "lancedb" %}
{% set version = "0.21.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lancedb/lancedb/archive/python-v{{ version }}.tar.gz
  sha256: 0725a1b5d3d80658e55f596ba7dac362c6970b12007ab3af8f91165823563db0

build:
  number: 0
  skip: true  # [py<39]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - {{ compiler("rust") }}
    - cargo-bundle-licenses
    - pkg-config
    - libprotobuf
  host:
    - python
    - maturin >=1.4
    - pip
    - openssl
  run:
    - python
    - deprecation
    - numpy
    - overrides >=0.7
    - packaging
    - pyarrow >=16
    - pydantic >=1.10
    - tqdm >=4.27.0
    - lance-namespace==0.0.6
    # Listed as optional but, actually required at runtime for core APIs.
    - pylance >=0.25
  run_constrained:
    # embeddings
    - requests >=2.31.0
    - openai >=1.6.1
    - colpali-engine >=0.3.10
    - boto3 >=1.28.57
    - awscli >=1.29.57
    - botocore >=1.31.57
    - ollama >=0.3.0
    - ibm-watsonx-ai >=1.1.2

    #  Azure
    - adlfs >=2024.2.0

test:
  imports:
    - lancedb
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lancedb/lancedb
  summary: Developer-friendly, serverless vector database for AI applications
  description: |
    LanceDB is an embedded vector database for AI applications and retrieval-augmented generation.
    It stores vectors and metadata on local disk or cloud object storage, supports multimodal search,
    and integrates with Python data tooling (including PyArrow and Pandas) without running a
    separate database server.
  license: Apache-2.0
  license_family: APACHE
  license_file: 
    - LICENSE
    - THIRDPARTY.yml
  doc_url: https://docs.lancedb.com
  dev_url: https://github.com/lancedb/lancedb

extra:
  recipe-maintainers:
    - moritzwilksch
    - mediocretech
    - jan-janssen
